
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secret-sync
  namespace: quantum-wallet
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: api-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /quantum-wallet/DATABASE_URL
    - secretKey: FIREBASE_PROJECT_ID
      remoteRef:
        key: /quantum-wallet/FIREBASE_PROJECT_ID
    - secretKey: REDIS_URL
      remoteRef:
        key: /quantum-wallet/REDIS_URL
    - secretKey: ADMIN_UID
      remoteRef:
        key: /quantum-wallet/ADMIN_UID
