
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-secret-store
  namespace: quantum-wallet
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: https://YOUR_KEY_VAULT_NAME.vault.azure.net/
