
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quantum-wallet-api.fullname" . }}-secrets
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  FIREBASE_PROJECT_ID: {{ .Values.secrets.FIREBASE_PROJECT_ID | quote }}
  REDIS_URL: {{ .Values.secrets.REDIS_URL | quote }}
  ADMIN_UID: {{ .Values.secrets.ADMIN_UID | quote }}
