
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-collector.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "otel-collector.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "otel-collector.fullname" . }}
    spec:
      containers:
        - name: collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["--config=/etc/otelcol/config.yaml"]
          ports:
            - name: otlp-http
              containerPort: 4318
          volumeMounts:
            - name: cfg
              mountPath: /etc/otelcol
      volumes:
        - name: cfg
          configMap:
            name: {{ include "otel-collector.fullname" . }}
