
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
spec:
  selector:
    app: {{ include "otel-collector.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: otlp-http
